export const TESOURO ={
 SITE: 'https://www.tesourodireto.com.br/',
 COOKIE:'#onetrust-accept-btn-handler',
 MENU: '.td-menu-trigger',
 CONHECA:':nth-child(1) > .td-nav__list-item__link',
 TESOURODIRETO:':nth-child(1) > .td-nav__sublist > :nth-child(1) > .td-nav__sublist__link',
 REGRAS:':nth-child(1) > .td-nav__sublist > :nth-child(2) > .td-nav__sublist__link',
 BANCOS:':nth-child(1) > .td-nav__sublist > :nth-child(3) > .td-nav__sublist__link',
 INSTITUCIONAL: ':nth-child(4) > .td-nav__sublist__link',
 BARRA: '.td-search-bar',
 BARRAPESQUISA: '#field-search-card-list',
 FILTRAR:'.td-filter-select__placeholder',
 FILTRO1: ':nth-child(1) > label > .td-filter-select__checkmark',
 FILTRO2: ':nth-child(2) > label > .td-filter-select__checkmark',
 FILTRO3: ':nth-child(2) > label > .td-filter-select__checkmark',
 APLICAR: '.td-filter-select__buttons',
 TEXTO1: 'RICO',
 TEXTO2: '1234',
 TEXTO3:'$%#%%$',
 FECHAR:'.td-notification__icon--close',
 TITULO: '.secundary-heading > strong',
 TITULO2:'.td-internal-heading > .secundary-heading',
 TITULO3: '.secundary-heading',
 TITULO4: ':nth-child(2) > .td-internal-heading > .secundary-heading',
 TITULO5: '.td-institucional__nossa-historia > .td-internal-wrapper--no-mobile > .td-internal-heading > .secundary-heading',

}

